spring:
  application:
    name: spring-ai-financial-rag

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

    vectorstore:
      pgvector:
        initialize-schema: true

  docker:
    compose:
      lifecycle-management: start_only

logging:
  level:
    org:
      apache:
        pdfbox:
          pdmodel:
            font:
              FileSystemFontProvider: ERROR
