## OpenRouter##
spring:
  ai:
    openai:
      base-url: https://openrouter.ai
      api-key: ${OPENROUTER_API_KEY}
      chat:
        completions-path: /api/v1/chat/completions
        options:
          model: ${chat-model}

#chat-model: deepseek/deepseek-chat-v3-0324:free
chat-model: qwen/qwen3-coder:free
